Add ability to override base directory for module deployment. Version 1.2.1
git-svn-id: https://module-manager.googlecode.com/svn/trunk@45 cc6c7596-0e12-11df-8365-8ba2325951e3

diff --git a/modman b/modman
--- a/modman
+++ b/modman
@@ -21,27 +21,27 @@
 #    - The following common utilities must be locatable in your $PATH
 #       grep (POSIX), find, ln, cp, basename, dirname, readlink
 
-version="1.2"
+version="1.2.1"
 script=${0##*/}
 usage="\
 Module Manager (v$version)
 
 Global Commands: $script <command>
 ------------------------------
-  init           initialize the current directory as the modman root
-  list           list all valid modules that are currently checked out
-  update-all     update all modules that are currently checked out
-  deploy-all     deploy all modules (no VCS interaction)
-  repair         rebuild all modman-created symlinks (no updates performed)
-  --version      display the modman script's version
+  init [basedir]     initialize the pwd (or [basedir]) as the modman deploy root
+  list               list all valid modules that are currently checked out
+  update-all         update all modules that are currently checked out
+  deploy-all         deploy all modules (no VCS interaction)
+  repair             rebuild all modman-created symlinks (no updates performed)
+  --version          display the modman script's version
 
 Module Actions: $script <module> <action> [<options>]
 ------------------------------
-  checkout       checkout a new modman compatible module using subversion
-  clone          checkout a new modman compatible module using git
-  update         update module using the appropriate SCM
-  deploy         deploy an existing module (SCM not required)
-  deploy --copy  deploy with hardlinks instead of symlinks (not recommended)
+  checkout           checkout a new modman compatible module using subversion
+  clone              checkout a new modman compatible module using git
+  update             update module using the appropriate SCM
+  deploy             deploy an existing module (SCM not required)
+  deploy --copy      deploy with hardlinks instead of symlinks (not recommended)
 
 Writing modman modules:
 ------------------------------
@@ -114,7 +114,14 @@ colin@mollenhour.com
 ###########################
 # Handle "init" command, simply create .modman directory
 if [ "$1" = "init" ]; then
-  mkdir .modman && echo "Initialized Module Manager at `pwd`"
+  basedir=$2
+  [[ -n "$basedir" && -d "$basedir" ]] || { echo "$basedir is not a directory."; exit 1; }
+  mkdir .modman || { echo "Could not create .modman directory" && exit 1; }
+  if [ -n "$basedir" ]; then
+    echo "$basedir" > .modman/.basedir
+    basedir="with basedir at $basedir"
+  fi
+  echo "Initialized Module Manager at $(pwd) $basedir"
   exit 0
 ###########################
 # Handle "--help" command
@@ -135,11 +142,20 @@ root=$_pwd
 while ! [ -d $root/.modman ]; do
   if [ "$root" = "/" ]; then echo -e $mm_not_found && exit 1; fi
   cd .. || { echo -e "ERROR: Could not traverse up from $root\n$mm_not_found" && exit 1; }
-  root=`pwd`
+  root=$(pwd)
 done
 
 mm=$root/.modman      # path to .modman
 FORCE=0               # --force option off by default
+
+# Allow a different root to be specified as the base dir for deploying modules
+if [ -r $mm/.basedir ]; then
+  newroot=$(cat $mm/.basedir)
+  if [ -d $newroot ]; then
+    cd $newroot || { echo -e "Could not change dir to basedir specified in .basedir file: $newroot" && exit 1; }
+    root=$(pwd)
+  fi
+fi
 
 #############################################################
 # Check for existence of a module directory and modman file
@@ -326,7 +342,7 @@ elif [ "$1" = "deploy-all" ]; then
   if [ -n "$2" ]; then echo "Too many arguments to deploy-all command."; exit 1; fi
   for module in `ls $mm`; do
     test -d $mm/$module || continue;
-    require_wc $module && echo "Deploying $module"
+    require_wc $module && echo "Deploying $module to $root"
     create_links $mm/$module/modman && echo -e "Deployment of $module complete.\n"
   done
   remove_dead_links $root
@@ -357,9 +373,10 @@ elif [ "$1" = "update-all" ]; then
 # Handle "repair" command
 elif [ "$1" = "repair" ]; then
   if [ "$2" == "--force" ]; then FORCE=1; shift; fi
-  mv $mm $root/.modman-repairing || { echo "Could not temporarily rename .modman directory"; exit 1; }
+  echo "Repairing links, do not interrupt."
+  mv $mm $mm-repairing || { echo "Could not temporarily rename .modman directory."; exit 1; }
   remove_dead_links $root
-  mv $root/.modman-repairing $mm || { echo "Could not restore .modman directory"; exit 1; }
+  mv $mm-repairing $mm || { echo "Could not restore .modman directory."; exit 1; }
   for module in `ls $mm`; do
     test -d $mm/$module || continue;
     require_wc $module && create_links $mm/$module/modman && echo -e "Repaired $module.\n"
@@ -373,7 +390,7 @@ fi
 # Discover if modman is run from within a module directory
 cd $_pwd
 module=''
-while [ "$root" != "$(pwd)" ]; do
+while [ "$(dirname $mm)" != "$(pwd)" && "$(pwd)" != "/" ]; do
   modpath=`pwd`
   if [ "$mm" = "$(dirname $modpath)" ]; then
     module=$(basename $modpath)
